//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartMetMfcUtils.rc
//
#define IDD_DIALOG_DATA_LOADINGPROBLEMS 160
#define IDD_DIALOG_DROP_FILE_WARNING    202
#define IDD_DIALOG_LOAD_DATA_INCOMPLETE_WARNING 214
#define IDD_DIALOG_GET_DIRECTORY_NAME   234
#define IDD_DIALOG_WITH_RICH_EDIT       250
#define IDC_STATIC_Text                 1051
#define IDC_RICHEDIT_TEXT_SECTION       1387
#define IDC_EDIT_DIRECTORY_NAME         1485
#define IDC_STATIC_DATA_LOADING_ERROR_STRING 1728
#define IDD_DIALOG_DATA_CHECK_PROP      6000
#define IDC_BUTTON_ACKNOWLEDGE          6001
#define IDB_BITMAP_DATA_CHECK_SYMBOL    6001
#define IDC_CHECK_USE                   6002
#define IDC_CHECK_SHOW_ON_MAP           6003
#define IDB_BITMAP_DATA_CHECK_SAMPLE    6003
#define IDC_STATIC_Check_DESCRIPTION    6004
#define IDD_DIALOG_DATA_CHECK_OPTIONS_PROB 6004
#define IDC_STATIC_STATUS_IMAGE         6005
#define IDC_STATIC_DATA_CHECK_IMAGE     6006
#define IDC_BUTTON_DATA_CHECK_SAVE      6006
#define IDB_BITMAP_DOUBLE_GREEN_LED2    6006
#define IDB_BITMAP_DOUBLE_GREEN_LED     6006
#define IDC_BUTTONDATA_CHECK_REMOVE     6007
#define IDC_LIST_DATA_CHECKS            6008
#define IDC_EDIT_NAME                   6009
#define IDC_STATIC_NAME_STR             6011
#define IDC_STATIC_AREA_STR             6012
#define IDC_COMBO_AREA                  6013
#define IDC_STATIC_SELECT_DATA_STR      6014
#define IDC_COMBO_DATA                  6015
#define IDB_BITMAP_GUS_ICON_EDIT_SKIN   6016
#define ID_SEARCHOPTION_CASESENSITIVE   6017
#define ID_SEARCHOPTION_MATCHANYWHERE   6018
#define IDR_MENU_GUS_ICON_EDIT          6019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6020
#define _APS_NEXT_COMMAND_VALUE         46000
#define _APS_NEXT_CONTROL_VALUE         6020
#define _APS_NEXT_SYMED_VALUE           6020
#endif
#endif
