INSERT INTO translation_sonera VALUES ('1-aamusta','200',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-aamuun','201',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-alkaen','202',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-illasta','203',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-iltaan','204',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-na','205',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-puoleiseksi tuuleksi','206',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-puoleista tuulta','207',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-suunnasta','208',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-suuntaan','209',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-tuuleksi','210',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-tuulta','211',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('1-vastaisena yönä','212',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-aamusta','213',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-aamuun','214',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-alkaen','215',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-illasta','216',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-iltaan','217',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-na','218',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-puoleiseksi tuuleksi','219',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-puoleista tuulta','220',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-suunnasta','221',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-suuntaan','222',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-tuuleksi','223',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-tuulta','224',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('2-vastaisena yönä','225',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-aamusta','226',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-aamuun','227',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-alkaen','228',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-illasta','229',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-iltaan','230',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-na','231',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-puoleiseksi tuuleksi','232',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-puoleista tuulta','233',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-suunnasta','234',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-suuntaan','235',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-tuuleksi','236',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-tuulta','237',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('3-vastaisena yönä','238',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-aamusta','239',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-aamuun','240',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-alkaen','241',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-illasta','242',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-iltaan','243',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-na','244',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-puoleiseksi tuuleksi','245',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-puoleista tuulta','246',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-suunnasta','247',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-suuntaan','248',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-tuuleksi','249',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-tuulta','250',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('4-vastaisena yönä','251',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-aamusta','252',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-aamuun','253',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-alkaen','254',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-illasta','255',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-iltaan','256',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-na','257',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-puoleiseksi tuuleksi','258',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-puoleista tuulta','259',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-suunnasta','260',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-suuntaan','261',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-tuuleksi','262',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-tuulta','263',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-vastaisena yönä','264',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('5-vuorokauden sää','265',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-aamusta','266',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-aamuun','267',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-alkaen','268',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-illasta','269',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-iltaan','270',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-na','271',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-puoleiseksi tuuleksi','272',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-puoleista tuulta','273',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-suunnasta','274',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-suuntaan','275',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-tuuleksi','276',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-tuulta','277',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('6-vastaisena yönä','278',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-aamusta','279',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-aamuun','280',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-alkaen','281',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-illasta','282',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-iltaan','283',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-na','284',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-puoleiseksi tuuleksi','285',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-puoleista tuulta','286',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-suunnasta','287',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-suuntaan','288',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-tuuleksi','289',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-tuulta','290',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('7-vastaisena yönä','291',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('8-puoleiseksi tuuleksi','292',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('8-puoleista tuulta','293',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('8-suunnasta','294',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('8-suuntaan','295',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('8-tuuleksi','296',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('8-tuulta','297',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aamulla','298',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aamupäivällä','299',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aamupäivästä alkaen','300',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aamusta alkaen','301',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aamuyöllä','302',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aamuyöstä alkaen','303',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ajoittain lumisadetta','304',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ajoittain sadetta','305',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ajoittain sateista','306',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ajoittain ukkosta','307',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aland:lle','308',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('alempi','309',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('alin suhteellinen kosteus','310',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('alkavan','311',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('alueen yli','312',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('aluksi','313',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ankaran hallan todennäköisyys','314',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('astetta','315',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('asti','316',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('edelleen','317',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('enimmäkseen','318',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ensi yönä','319',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('etela-karjala:lle','320',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('etela-pohjanmaa:lle','321',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('etela-savo:lle','322',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hallan todennäköisyys','323',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hame:lle','324',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('heikkenevää','325',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('heikkoa sadetta','326',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('heikkoa','327',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('heikoksi','328',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hieman alempi','329',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hieman korkeampi','330',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hieman pienempi','331',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hieman suurempi','332',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hirmumyrskyksi','333',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('hirmumyrskyä','334',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomattavasti alempi','335',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomattavasti korkeampi','336',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomattavasti lämpimämpi','337',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomattavasti pienempi','338',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomattavasti suurempi','339',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomenna','340',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('huomisaamuna','341',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('illalla','342',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('illasta alkaen','343',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('iltapäivällä','344',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('iltapäivästä alkaen','345',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('iltayöllä','346',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('iltayöstä alkaen','347',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kainuu:lle','348',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kello','349',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keski-pohjanmaa:lle','350',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keski-suomi:lle','351',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskilämpötila','352',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskimääräinen alin lämpötila','353',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskimääräinen ylin lämpötila','354',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskipäivällä','355',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskipäivästä alkaen','356',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskiyöllä','357',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('keskiyöstä alkaen','358',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kohtalaiseksi','359',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kohtalaista','360',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('koillismaa:lle','361',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('korkeampi','362',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('korkeapaine','363',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('korkeapaineen alue','364',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kosteammaksi','365',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kovaa','366',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kovaksi','367',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kuivemmaksi','368',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('kymenlaakso:lle','369',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('laaja','370',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lansi-lappi:lle','371',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('leviää','372',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('liikkuu','373',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('loittonee','374',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lopuksi','375',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lumi-','376',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lumikuuroja','377',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lumisadetta','378',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lähestyy','379',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lämpenee','380',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lämpimämpi','381',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('lämpötila','382',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('m/s','383',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('mahdollisesti ukkosta','384',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('matalapaine','385',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('matalapaineen alue','386',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('melko selkeää','387',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('metriä sekunnissa','388',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('miinus','389',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('millimetriä','390',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('monin paikoin enemmän','391',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('monin paikoin','392',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('muuttuu','393',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('myrskyksi','394',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('myrskyä','395',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('navakaksi','396',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('navakkaa','397',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('noin','398',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('nyland:lle','399',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('odotettavissa','400',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('on','401',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('osterbotten:lle','402',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('paijat-hame:lle','403',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('paikoin enemmän','404',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('paikoin','405',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pienempi','406',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pilvistyvää','407',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pilvistä','408',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pirkanmaa:lle','409',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pohjois-karjala:lle','410',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pohjois-lappi:lle','411',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pohjois-pohjanmaa:lle','412',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('pohjois-savo:lle','413',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('poutaa','414',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('puolipilvistä','415',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('päivien ylin lämpötila','416',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('päivällä','417',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('päivälämpötila','418',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('päivän ylin lämpötila','419',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('rannikolla','420',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('runsasta sadetta','421',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('räntä-','422',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('räntäsadetta','423',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sadealue','424',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sadesumma','425',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sadetta','426',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sakeaa lumisadetta','427',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sakeita lumikuuroja','428',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sama','429',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('satakunta:lle','430',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('selkenevää','431',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('selkeää','432',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('seuraava yö','433',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('seuraavana päivänä','434',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('seuraavana yönä','435',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('suunnaltaan vaihtelevaa','436',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('suunnilleen sama','437',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('suurempi','438',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('syvenee','439',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sää on epävakaista','440',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sää','441',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('sääennuste','442',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tai','443',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tuuli heikkenee','444',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tuuli tyyntyy','445',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tuuli voimistuu','446',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tuuli','447',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tuulta','448',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tyyneksi','449',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tyyntä','450',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('tänään','451',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('uusimaa:lle','452',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('vahvistuu','453',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('vaihtelevaa pilvisyyttä','454',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('varsinais-suomi:lle','455',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('vesi-','456',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('vesisadetta','457',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('viilenee','458',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('viiva','459',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('voimakkaita kuuroja','460',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('voimistuvaa','461',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('vähäisiä kuuroja','462',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('vähäistä lumisadetta','463',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('yli','464',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('ylihuomenna','465',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('yöllä','466',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('yölämpötila','467',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('yön alin lämpötila','468',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('yöstä alkaen','469',NULL,'mheiskan');
INSERT INTO translation_sonera VALUES ('öiden alin lämpötila','470',NULL,'mheiskan');
