#pragma once

#include "NFmiGlobals.h"
#include "catlog/catlog.h"
#include "FmiEditorModifyToolMode.h"
#include "FmiSmartMetEditingMode.h"
#include "ControlPointAcceleratorActions.h"
#include "SmartMetViewId.h"
#include "CombinedMapHandlerInterface.h"

#include "boost/shared_ptr.hpp"

class NFmiBetaProductionSystem;
class NFmiMetTime;
class NFmiViewSettingMacro;
class NFmiMapViewDescTop;
class NFmiDrawParamList;
class NFmiInfoOrganizer;
class NFmiBetaProduct;
class CBitmap;
class NFmiSatelliteImageCacheSystem;
class NFmiFastQueryInfo;
class NFmiDrawParam;
class NFmiArea;
class NFmiApplicationWinRegistry;
class NFmiEditMapDataListHandler;
class NFmiCaseStudySystem;
class NFmiHelpDataInfoSystem;
class NFmiProducerSystem;
class NFmiApplicationDataBase;
class NFmiIgnoreStationsData;
class NFmiDataLoadingInfo;
class NFmiModelDataBlender;
class CWnd;
class NFmiCrossSectionSystem;
class NFmiMenuItemList;
class NFmiDataQualityChecker;
class NFmiTrajectorySystem;
class NFmiMetEditorOptionsData;
class NFmiTimeBag;
class NFmiParamBag;
class NFmiMTATempSystem;
class NFmiToolBox;
class NFmiAnalyzeToolData;
class NFmiCPManagerSet;
class NFmiEditorControlPointManager;
class NFmiFixedDrawParamSystem;
class NFmiSmartToolInfo;
class NFmiMacroParamSystem;
class NFmiAutoComplete;
class NFmiMenuItem;
class NFmiEditDataUserList;
class NFmiHelpEditorSystem;
class Q2ServerInfo;
class NFmiLocationSelectionTool;
class NFmiSynopPlotSettings;
class NFmiSynopStationPrioritySystem;
class NFmiLightWeightViewSettingMacro;
class NFmiWindTableSystem;
class NFmiMacroParamDataCache;
class NFmiGdiPlusImageMapHandler;
class CDC;
class NFmiParameterInterpolationFixer;
class NFmiMacroParamDataGenerator;

namespace HakeMessage
{
    class Main;
}
namespace CtrlViewUtils
{
    struct GraphicalInfo;
}
namespace AddParams
{
    class ParameterSelectionSystem;
}

// Interface that is meant to be used by MFC views in libraries in SmartMet part of code.
class SmartMetDocumentInterface
{
public:
    using GetSmartMetDocumentInterfaceImplementationCallBackType = std::function<SmartMetDocumentInterface*(void)>;
    // Tämä pitää asettaa johonkin konkreettiseen funktioon, jotta käyttäjä koodi saa käyttöönsä halutun interface toteutuksen
    static GetSmartMetDocumentInterfaceImplementationCallBackType GetSmartMetDocumentInterfaceImplementation;

	virtual ~SmartMetDocumentInterface() = default;

    virtual NFmiBetaProductionSystem& BetaProductionSystem() = 0;
    virtual bool BetaProductGenerationRunning() = 0;
    virtual void BetaProductGenerationRunning(bool newValue) = 0;
    virtual void SetAllViewIconsDynamically() = 0;
    virtual FmiLanguage Language() = 0;
    virtual const std::string& RootViewMacroPath() = 0;
    virtual const NFmiMetTime& CurrentTime(unsigned int theDescTopIndex) = 0;
    virtual void LoadViewMacroInfo(NFmiViewSettingMacro &theViewMacro, bool fTreatAsViewMacro) = 0;
    virtual void FillViewMacroInfo(NFmiViewSettingMacro &theViewMacro, const std::string &theName, const std::string &theDescription) = 0;
    virtual void LogAndWarnUser(const std::string &theMessageStr, const std::string &theDialogTitleStr, CatLog::Severity severity, CatLog::Category category, bool justLog, bool addAbortOption = false, bool flushLogger = false) = 0;
    virtual void RefreshApplicationViewsAndDialogs(const std::string &reasonForUpdate, bool fMakeAreaViewDirty = false, bool fClearCache = false, int theWantedMapViewDescTop = -1) = 0;
    virtual void RefreshApplicationViewsAndDialogs(const std::string& reasonForUpdate, SmartMetViewId updatedViewsFlag) = 0;
    virtual NFmiMapViewDescTop* MapViewDescTop(unsigned int theIndex) = 0;
    virtual NFmiDrawParamList* DrawParamListWithRealRowNumber(unsigned int theDescTopIndex, int theRealRowIndex) = 0;
    virtual NFmiInfoOrganizer* InfoOrganizer() = 0;
    virtual bool LoadViewMacroFromBetaProduct(const std::string &theAbsoluteVieMacroPath, std::string &theErrorStringOut, bool justLogMessages) = 0;
    virtual void SetCurrentGeneratedBetaProduct(const NFmiBetaProduct* theBetaProduct) = 0;
    virtual const NFmiBetaProduct* GetCurrentGeneratedBetaProduct() = 0;
    virtual bool CurrentTime(unsigned int theDescTopIndex, const NFmiMetTime& newCurrentTime, bool fStayInsideAnimationTimes = false) = 0;
    virtual NFmiSatelliteImageCacheSystem& SatelliteImageCacheSystem() = 0;
    virtual void MakeDrawedInfoVectorForMapView(std::vector<boost::shared_ptr<NFmiFastQueryInfo> > &theInfoVector, boost::shared_ptr<NFmiDrawParam> &theDrawParam, const boost::shared_ptr<NFmiArea> &theArea) = 0;
    virtual NFmiApplicationWinRegistry& ApplicationWinRegistry() = 0;
    virtual const NFmiPoint& BrushSize() = 0;
    virtual void BrushSize(const NFmiPoint& theSize) = 0;
    virtual NFmiEditMapDataListHandler* DataLists() = 0;
    virtual bool UseMaskWithBrush() = 0;
    virtual void UseMaskWithBrush(bool newState) = 0;
    virtual double BrushValue() = 0;
    virtual void BrushValue(double newValue) = 0;
    virtual float BrushToolLimitSettingValue() = 0;
    virtual void BrushToolLimitSettingValue(float newValue) = 0;
    virtual int BrushToolLimitSetting() = 0;
    virtual void BrushToolLimitSetting(int newValue) = 0;
    virtual CtrlViewUtils::FmiEditorModifyToolMode ModifyToolMode() = 0;
    virtual void ModifyToolMode(CtrlViewUtils::FmiEditorModifyToolMode newState) = 0;
    virtual boost::shared_ptr<NFmiDrawParam> ActiveDrawParamFromActiveRow(unsigned int theDescTopIndex) = 0;
    virtual int AbsoluteActiveViewRow(unsigned int theDescTopIndex) = 0;
    virtual void AbsoluteActiveViewRow(unsigned int theDescTopIndex, int theAbsoluteActiveRowIndex) = 0;
    virtual double BrushSpecialParamValue() = 0;
    virtual void BrushSpecialParamValue(double newValue) = 0;
    virtual boost::shared_ptr<NFmiFastQueryInfo> EditedSmartInfo() = 0;
    virtual void OnButtonRedo() = 0;
    virtual void OnButtonUndo() = 0;
    virtual NFmiHelpDataInfoSystem* HelpDataInfoSystem() = 0;
    virtual NFmiProducerSystem& ProducerSystem() = 0;
    virtual NFmiProducerSystem& ObsProducerSystem() = 0;
    virtual NFmiProducerSystem& SatelImageProducerSystem() = 0;
    virtual NFmiCaseStudySystem& CaseStudySystem() = 0;
    virtual bool StoreCaseStudyMemory() = 0;
    virtual void CaseStudyToNormalMode() = 0;
    virtual NFmiCaseStudySystem& LoadedCaseStudySystem() = 0;
    virtual bool CaseStudyModeOn() = 0;
    virtual bool LoadCaseStudyData(const std::string &theCaseStudyMetaFile) = 0;
    virtual void UpdateEnableDataChangesToWinReg() = 0;
    virtual NFmiApplicationDataBase& ApplicationDataBase() = 0;
    virtual const std::string& WorkingDirectory() const = 0;
    virtual const std::string& ControlDirectory() const = 0;
    virtual const std::string& HelpDataPath() const = 0;
    virtual NFmiIgnoreStationsData& IgnoreStationsData() = 0;
    virtual NFmiDataLoadingInfo& GetUsedDataLoadingInfo() = 0;
    virtual NFmiModelDataBlender& ModelDataBlender() = 0;
    virtual CtrlViewUtils::FmiSmartMetEditingMode SmartMetEditingMode() = 0;
    virtual void SmartMetEditingMode(CtrlViewUtils::FmiSmartMetEditingMode newValue, bool modifySettings) = 0;
    virtual void SetDataLoadingProducerIndexVector(const std::vector<int>& theIndexVector) = 0;
    virtual bool Printing() = 0;
    virtual void Printing(bool newStatus) = 0;
    virtual void Printing(unsigned int theMapViewDescTopIndex, bool newStatus) = 0;
    virtual boost::shared_ptr<NFmiDrawParam> DefaultEditedDrawParam() = 0;
    virtual double DrawObjectScaleFactor() = 0;
    virtual void DrawObjectScaleFactor(double newValue) = 0;
    virtual void TransparencyContourDrawView(CWnd *theView) = 0;
    virtual CWnd* TransparencyContourDrawView() = 0;
    virtual bool IsToolMasterAvailable() const = 0;
    virtual void ToolMasterAvailable(bool newValue) = 0;
    virtual NFmiCrossSectionSystem* CrossSectionSystem() = 0;
    virtual bool ActivateParamSelectionDlgAfterLeftDoubleClick() = 0;
    virtual void ActivateParamSelectionDlgAfterLeftDoubleClick(bool newValue) = 0;
    virtual void ActivateParameterSelectionDlg(unsigned int theMapViewDescTopIndex) = 0;
    virtual bool OpenPopupMenu() = 0;
    virtual void OpenPopupMenu(bool newState) = 0;
    virtual const NFmiPoint& CrossSectionViewSizeInPixels() = 0;
    virtual void CrossSectionViewSizeInPixels(const NFmiPoint& newSize) = 0;
    virtual bool ShowWaitCursorWhileDrawingView() = 0;
    virtual NFmiMenuItemList* PopupMenu() = 0;
    virtual void MapViewDirty(unsigned int theDescTopIndex, bool makeNewBackgroundBitmap, bool clearMapViewBitmapCacheRows, bool redrawMapView, bool clearMacroParamDataCache, bool clearEditedDataDependentCaches, bool updateMapViewDrawingLayers) = 0;
    virtual void ForceStationViewRowUpdate(unsigned int theDescTopIndex, unsigned int theRealRowIndex) = 0;
    virtual bool MakePopUpCommandUsingRowIndex(unsigned short theCommandID) = 0;
    virtual NFmiDataQualityChecker& DataQualityChecker() = 0;
    virtual NFmiTrajectorySystem* TrajectorySystem() = 0;
    virtual bool ViewBrushed() = 0;
    virtual void ViewBrushed(bool newState) = 0;
    virtual NFmiPoint GetPrintedMapAreaOnScreenSizeInPixels(unsigned int theDescTopIndex) = 0;
    virtual bool EditedPointsSelectionChanged() = 0;
    virtual bool EditedPointsSelectionChanged(bool newValue) = 0;
    virtual const NFmiPoint& ToolTipLatLonPoint() const = 0;
    virtual void ToolTipLatLonPoint(const NFmiPoint& theLatLon) = 0;
    virtual bool MiddleMouseButtonDown() = 0;
    virtual void MiddleMouseButtonDown(bool newState) = 0;
    virtual bool MouseCaptured() = 0;
    virtual void MouseCaptured(bool newState) = 0;
    virtual void MustDrawTempView(bool newValue) = 0;
    virtual bool MustDrawTempView() = 0;
    virtual void MustDrawCrossSectionView(bool newValue) = 0;
    virtual bool MustDrawCrossSectionView() = 0;
    virtual void UpdateTempView() = 0;
    virtual void UpdateCrossSectionView() = 0;
    virtual bool ShowMouseHelpCursorsOnMap() = 0;
    virtual void ShowMouseHelpCursorsOnMap(bool newState) = 0;
    virtual NFmiMetEditorOptionsData& MetEditorOptionsData() = 0;
    virtual void SetSelectedMapHandler(unsigned int theDescTopIndex, unsigned int newMapIndex) = 0;
    virtual void OnButtonDataArea(unsigned int theDescTopIndex) = 0;
    virtual bool SetMapViewGrid(unsigned int theDescTopIndex, const NFmiPoint &newValue) = 0;
    virtual void OnShowTimeString(unsigned int theDescTopIndex) = 0;
    virtual void OnChangeParamWindowPosition(unsigned int mapViewDescTopIndex, bool forward) = 0;
    virtual void OnShowGridPoints(unsigned int theMapViewIndex) = 0;
    virtual bool SetDataToNextTime(unsigned int theDescTopIndex, bool fStayInsideAnimationTimes = false) = 0;
    virtual bool SetDataToPreviousTime(unsigned int theDescTopIndex, bool fStayInsideAnimationTimes = false) = 0;
    virtual bool ScrollViewRow(unsigned int theDescTopIndex, int theCount) = 0;
    virtual void OnToggleGridPointColor(unsigned int theDescTopIndex) = 0;
    virtual void OnToggleGridPointSize(unsigned int theDescTopIndex) = 0;
    virtual void OnEditSpaceOut(unsigned int theDescTopIndex) = 0;
    virtual void OnButtonRefresh(const std::string& message) = 0;
    virtual void OnShowProjectionLines() = 0;
    virtual void OnShowMasksOnMap(unsigned int theDescTopIndex) = 0;
    virtual void OnToggleShowNamesOnMap(unsigned int theDescTopIndex, bool fForward) = 0;
    virtual void OnChangeMapType(unsigned int theDescTopIndex, bool fForward) = 0;
    virtual void OnToggleLandBorderPenSize(unsigned int theDescTopIndex) = 0;
    virtual void OnToggleLandBorderDrawColor(unsigned int theDescTopIndex) = 0;
    virtual void OnAcceleratorBorrowParams(unsigned int theDescTopIndex, int row) = 0;
    virtual void OnAcceleratorMapRow(unsigned int theDescTopIndex, int theStartingRow) = 0;
    virtual void OnAcceleratorToggleKeepMapRatio() = 0;
    virtual void OnToggleOverMapBackForeGround(unsigned int theDescTopIndex) = 0;
    virtual std::string GetToolTipString(unsigned int commandID, std::string &theMagickWord) = 0;
    virtual void ActivateZoomDialog(int theWantedDescTopIndex) = 0;
    virtual void MakeSwapBaseArea(unsigned int theDescTopIndex) = 0;
    virtual void SwapArea(unsigned int theDescTopIndex) = 0;
    virtual void CopyMapViewDescTopParams(unsigned int theDescTopIndex) = 0;
    virtual void PasteMapViewDescTopParams(unsigned int theDescTopIndex) = 0;
    virtual void CopyDrawParamsFromMapViewRow(unsigned int theDescTopIndex) = 0;
    virtual void PasteDrawParamsToMapViewRow(unsigned int theDescTopIndex) = 0;
    virtual void ToggleTimeControlAnimationView(unsigned int theDescTopIndex) = 0;
    virtual void OnAcceleratorSetHomeTime(int theMapViewDescTopIndex) = 0;
    virtual void PanMap(int theMapViewDescTopIndex, boost::shared_ptr<NFmiArea> &theMapArea, const NFmiPoint &theMousePoint, const NFmiPoint &theZoomDragUpPoint) = 0;
    virtual void ZoomMapInOrOut(int theMapViewDescTopIndex, boost::shared_ptr<NFmiArea> &theMapArea, const NFmiPoint &theMousePoint, double theZoomFactor) = 0;
    virtual const NFmiTimeBag& EditedDataTimeBag() = 0;
    virtual int FilterDialogUpdateStatus() = 0;
    virtual void FilterDialogUpdateStatus(int newState) = 0;
    virtual bool DoAreaFiltering() = 0;
    virtual bool DoTimeFiltering() = 0;
    virtual int FilterFunction() = 0;
    virtual void FilterFunction(int newFilter) = 0;
    virtual bool UseMasksWithFilterTool() = 0;
    virtual void UseMasksWithFilterTool(bool newStatus) = 0;
    virtual void SetTestFilterMask(int newValue) = 0;
    virtual int GetTestFilterMask() = 0;
    virtual void ResetFilters() = 0;
    virtual int FilteringParameterUsageState() = 0;
    virtual void FilteringParameterUsageState(int newState) = 0;
    virtual bool UseTimeInterpolation() = 0;
    virtual void UseTimeInterpolation(bool newState) = 0;
    virtual NFmiParamBag& FilteringParamBag() = 0;
    virtual void FilteringParamBag(const NFmiParamBag& newBag) = 0;
    virtual bool DoCombineModelAndKlapse() = 0;
    virtual NFmiMTATempSystem& GetMTATempSystem() = 0;
    virtual bool ShowToolTipTimeView() = 0;
    virtual void ShowToolTipTimeView(bool newValue) = 0;
    virtual bool ShowToolTipTempView() = 0;
    virtual void ShowToolTipTempView(bool newValue) = 0;
    virtual int SoundingViewWindBarbSpaceOutFactor() = 0;
    virtual void SoundingViewWindBarbSpaceOutFactor(int newValue) = 0;
    virtual void DoTEMPDataUpdate(const std::string &theTEMPCodeTextStr, std::string &theTEMPCodeCheckReportStr, bool fJustCheckTEMPCode = false) = 0;
    virtual const std::string& LastTEMPDataStr() = 0;
    virtual void ClearTEMPData() = 0;
    virtual bool TimeSerialViewDirty() = 0;
    virtual void TimeSerialViewDirty(bool newValue) = 0;
    virtual void DrawOverBitmapThings(NFmiToolBox * theGTB) = 0;
    virtual bool MouseCapturedInTimeWindow() = 0;
    virtual void MouseCapturedInTimeWindow(bool newValue) = 0;
    virtual CombinedMapHandlerInterface::MapViewDescTopVector& MapViewDescTopList() = 0;
    virtual bool IsMasksUsedInTimeSerialViews() = 0;
    virtual void UseMasksInTimeSerialViews(bool newValue) = 0;
    virtual bool UseCPGridCrop() = 0;
    virtual void UseCPGridCrop(bool newValue) = 0;
    virtual const NFmiPoint& TimeSerialViewSizeInPixels() const = 0;
    virtual void TimeSerialViewSizeInPixels(const NFmiPoint &newValue) = 0;
    virtual bool UseTimeSerialAxisAutoAdjust() = 0;
    virtual void UseTimeSerialAxisAutoAdjust(bool newValue) = 0;
    virtual bool AllowRightClickDisplaySelection() = 0;
    virtual void AllowRightClickDisplaySelection(bool newValue) = 0;
    virtual NFmiAnalyzeToolData& AnalyzeToolData() = 0;
    virtual bool UseMultiProcessCpCalc() = 0;
    virtual void UseMultiProcessCpCalc(bool newValue) = 0;
    virtual NFmiCPManagerSet& CPManagerSet() = 0;
    virtual boost::shared_ptr<NFmiEditorControlPointManager> CPManager(bool getOldSchoolCPManager = false) = 0;
    virtual bool TimeSerialDataViewOn() = 0;
    virtual void TimeSerialDataViewOn(bool newValue) = 0;
    virtual bool ShowHelperData1InTimeSerialView() = 0;
    virtual bool ShowHelperData2InTimeSerialView() = 0;
    virtual bool ShowHelperData3InTimeSerialView() = 0;
    virtual bool ShowHelperData4InTimeSerialView() = 0;
    virtual void ToggleShowHelperDatasInTimeView(int theCommand) = 0;
    virtual NFmiDrawParamList* TimeSerialViewDrawParamList() = 0;
    virtual void SetMapArea(unsigned int theDescTopIndex, const boost::shared_ptr<NFmiArea> &newArea) = 0;
    virtual const NFmiMetTime& ActiveMapTime() = 0;
    virtual const std::string& FileDialogDirectoryMemory() = 0;
    virtual bool MakeAndStoreFileDialogDirectoryMemory(const std::string& thePathAndFileName) = 0;
    virtual NFmiFixedDrawParamSystem& FixedDrawParamSystem() = 0;
    virtual void TakeDrawParamInUseEveryWhere(boost::shared_ptr<NFmiDrawParam> &theDrawParam, bool useInMap, bool useInTimeSerial, bool useInCrossSection, bool useWithViewMacros) = 0;
    virtual NFmiSmartToolInfo* SmartToolInfo() = 0;
    virtual std::shared_ptr<NFmiMacroParamSystem> MacroParamSystem() = 0;
    virtual bool DoSmartToolEditing(const std::string &theSmartToolText, const std::string &theRelativePathMacroName, bool fSelectedLocationsOnly) = 0;
    virtual std::string& SmartToolEditingErrorText() = 0;
    virtual void RemoveMacroParam(const std::string &theName) = 0;
    virtual void AddMacroParamToView(unsigned int theDescTopIndex, int theViewRow, const std::string &theName) = 0;
    virtual void AddMacroParamToCrossSectionView(int theViewRow, const std::string &theName) = 0;
    virtual const std::string& GetLatestMacroParamErrorText() = 0;
    virtual void RemoveAllParamsFromMapViewRow(unsigned int theDescTopIndex, int theRowIndex) = 0;
    virtual void RemoveAllParamsFromCrossSectionViewRow(int theRowIndex) = 0;
    virtual void SetMacroParamDataGridSize(int xSize, int ySize) = 0;
    virtual const std::vector<std::string>& SmartToolFileNames(bool updateList) = 0;
    virtual NFmiAutoComplete& AutoComplete() = 0;
    virtual void InvalidateMapView(bool bErase = true) = 0;
    virtual CtrlViewUtils::GraphicalInfo& GetGraphicalInfo(int theMapViewDescTopIndex) = 0;
    virtual AddParams::ParameterSelectionSystem& ParameterSelectionSystem() = 0;
    virtual void UpdateParameterSelectionSystem() = 0;
    virtual bool ExecuteCommand(const NFmiMenuItem &theMenuItem, int theViewIndex, int theViewTypeId) = 0;
    virtual int DataToDBCheckMethod() = 0;
    virtual void DataToDBCheckMethod(int newValue) = 0;
    virtual NFmiEditDataUserList& EditDataUserList() = 0;
    virtual NFmiHelpEditorSystem& HelpEditorSystem() = 0;
    virtual int SatelDataRefreshTimerInMinutes() = 0;
    virtual void SatelDataRefreshTimerInMinutes(int newValue) = 0;
    virtual const NFmiPoint& StationDataGridSize() = 0;
    virtual void StationDataGridSize(const NFmiPoint &newValue) = 0;
    virtual bool DoAutoLoadDataAtStartUp() const = 0;
    virtual void DoAutoLoadDataAtStartUp(bool newValue) = 0;
    virtual void SetMapViewCacheSize(double theNewSizeInMB) = 0;
    virtual void ReloadFixedDrawParams() = 0;
    virtual Q2ServerInfo& GetQ2ServerInfo() = 0;
    virtual void LastSelectedSynopWmoId(int theWmoId) = 0;
    virtual int LastSelectedSynopWmoId() = 0;
    virtual const NFmiPoint& GetSynopHighlightLatlon() = 0;
    virtual void SetHighlightedSynopStation(const NFmiPoint &theLatlon, int theWmoId, bool fShowHighlight) = 0;
    virtual bool SynopDataGridViewOn() = 0;
    virtual void SynopDataGridViewOn(bool newState) = 0;
    virtual std::vector<boost::shared_ptr<NFmiFastQueryInfo> > GetSortedSynopInfoVector(int theProducerId, int theProducerId2 = -1, int theProducerId3 = -1, int theProducerId4 = -1) = 0;
    virtual void ForceDrawOverBitmapThings(unsigned int originalCallerDescTopIndex, bool doOriginalView, bool doAllOtherMapViews) = 0;
    virtual NFmiLocationSelectionTool* LocationSelectionTool2() = 0;
    virtual NFmiParamBag& AllStaticParams() = 0;
    virtual NFmiSynopPlotSettings* SynopPlotSettings() = 0;
    virtual NFmiSynopStationPrioritySystem* SynopStationPrioritySystem() = 0;
    virtual std::vector<NFmiLightWeightViewSettingMacro>& ViewMacroDescriptionList() = 0;
    virtual bool RemoveViewMacro(const std::string& theMacroName) = 0;
    virtual void RefreshViewMacroList() = 0;
    virtual bool LoadViewMacro(const std::string &theName) = 0;
    virtual void StoreViewMacro(const std::string &theAbsoluteMacroFilePath, const std::string &theDescription) = 0;
    virtual bool CreateNewViewMacroDirectory(const std::string &thePath) = 0;
    virtual void UndoViewMacro() = 0;
    virtual void RedoViewMacro() = 0;
    virtual bool IsUndoableViewMacro() = 0;
    virtual bool IsRedoableViewMacro() = 0;
    virtual const std::vector<std::string>& CorruptedViewMacroFileList() const = 0;
    virtual void ChangeCurrentViewMacroDirectory(const std::string & theDirectoryName, bool fUseRootPathAsBase) = 0;
    virtual std::string GetRelativeViewMacroPath() = 0;
    virtual const std::vector<std::string>& ViewMacroFileNames(bool updateList) = 0;
    virtual NFmiWindTableSystem& WindTableSystem() = 0;
    virtual void SelectLocations(unsigned int theDescTopIndex, boost::shared_ptr<NFmiFastQueryInfo> &theInfo, const boost::shared_ptr<NFmiArea> &theMapArea,
        const NFmiPoint& theLatLon, const NFmiMetTime &theTime, int theSelectionCombineFunction, unsigned long theMask
        , bool fMakeMTAModeAdd, bool fDoOnlyMTAModeAdd) = 0;
    virtual void UpdateRowInLockedDescTops(unsigned int theOrigDescTopIndex) = 0;
    virtual int GetTimeRangeForWarningMessagesOnMapViewInMinutes() = 0;
    virtual bool MakeControlPointAcceleratorAction(ControlPointAcceleratorActions action, const std::string &updateMessage) = 0;
    virtual NFmiMacroParamDataCache& MacroParamDataCache() = 0;
    virtual bool DoMapViewOnSize(int mapViewDescTopIndex, const NFmiPoint &clientPixelSize, CDC* pDC) = 0;
    virtual NFmiGdiPlusImageMapHandler* GetMapHandlerInterface(int mapViewDescTopIndex) = 0;
    virtual bool ChangeTime(int theTypeOfChange, FmiDirection theDirection, unsigned long theMapViewIndex, double theAmountOfChange) = 0;
    virtual void SetHatchingToolmasterEpsilonFactor(float newEpsilonFactor) = 0;
    virtual CombinedMapHandlerInterface& GetCombinedMapHandlerInterface() = 0;
    virtual NFmiParameterInterpolationFixer& ParameterInterpolationFixer() = 0;
    virtual void ApplyUpdatedViewsFlag(SmartMetViewId updatedViewsFlag) = 0;
    virtual void UpdateMacroParamDataGridSizeAfterVisualizationOptimizationsChanged() = 0;
    virtual void OpenVisualizationsettingsDialog() = 0;
    virtual std::shared_ptr<NFmiViewSettingMacro> CurrentViewMacro() = 0;
    virtual void ToggleVirtualTimeMode(const std::string& logMessage) = 0;
    virtual bool VirtualTimeUsed() const = 0;
    virtual NFmiMacroParamDataGenerator& GetMacroParamDataGenerator() = 0;

#ifndef DISABLE_CPPRESTSDK
    virtual HakeMessage::Main& WarningCenterSystem() = 0;
#endif // DISABLE_CPPRESTSDK
};
