#pragma once

// FmiCombineDataThread.h

#include "stdafx.h"

#include <string>
#include <vector>

class NFmiHelpDataInfoSystem;

namespace CFmiCombineDataThread
{
	void InitCombineDataInfos(const NFmiHelpDataInfoSystem &theHelpDataInfoSystem, const std::string& smartMetBinariesDirectory); // t‰m‰ pit‰‰ kutsua ennen kuin threadi (DoThread) k‰ynnistet‰‰n ja kun cache-asetuksia muutetaan
	UINT DoThread(LPVOID pParam);
	void CloseNow(void);
	int WaitToClose(int theMilliSecondsToWait);
	void SetFirstTimeDelay(int theStartUpDelayInMS);
	std::string MakeDailyDataCombinationLogFilePath(bool putInQuotes);
}

namespace CFmiSoundingIndexDataThread
{
	void InitSoundingIndexDataInfos(NFmiHelpDataInfoSystem &theHelpDataInfoSystem, const std::string &autoGeneratedSoundingIndexBasePath); // t‰m‰ pit‰‰ kutsua ennen kuin threadi (DoThread) k‰ynnistet‰‰n
	UINT DoThread(LPVOID pParam);
	void CloseNow(void);
	int WaitToClose(int theMilliSecondsToWait);
	void SetFirstTimeDelay(int theStartUpDelayInMS);
}

