//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartMetThreads.rc
//
#define ID_MESSAGE_WORKING_THREAD_DATA_READ 10001
#define ID_MESSAGE_NEW_HAKE_WARNING_AVAILABLE 10002
#define ID_MESSAGE_MACRO_PARAMS_UPDATE  10003
#define ID_MESSAGE_WORKING_THREAD_DATA_READ2 10004
#define ID_MESSAGE_NEW_SEA_ICING_WARNING_AVAILABLE 10005
#define ID_MESSAGE_WORKING_THREAD_DATA_CHECK_RESULTS 10006
#define ID_MESSAGE_START_HISTORY_THREAD 10007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10001
#define _APS_NEXT_COMMAND_VALUE         50001
#define _APS_NEXT_CONTROL_VALUE         10001
#define _APS_NEXT_SYMED_VALUE           10007
#endif
#endif
