# SmartMet Linux minimal configuration

SmartMet
{
	PreConfigurationFiles = /home/mheiskan/hub/workstation/control_linux/paths_linux.conf

	ConfigurationFiles = ${localPath}/editor.conf
	ConfigurationFiles += ${localPath}/static_settings.conf
	ConfigurationFiles += ${localPath}/mapviewsettings.conf
}
