#pragma once

#include "SmartMetDocumentInterface.h"

class NFmiEditMapGeneralDataDoc;

// Interface that is meant to be used by MFC views in libraries in SmartMet part of code.
class SmartMetDocumentInterfaceForGeneralDataDoc : public SmartMetDocumentInterface
{
    NFmiEditMapGeneralDataDoc *itsDoc;
public:
    SmartMetDocumentInterfaceForGeneralDataDoc(NFmiEditMapGeneralDataDoc *theDoc);
    ~SmartMetDocumentInterfaceForGeneralDataDoc() = default;

    NFmiBetaProductionSystem& BetaProductionSystem() override;
    bool BetaProductGenerationRunning() override;
    void BetaProductGenerationRunning(bool newValue) override;
    void SetAllViewIconsDynamically() override;
    FmiLanguage Language() override;
    const std::string& RootViewMacroPath() override;
    const NFmiMetTime& CurrentTime(unsigned int theDescTopIndex) override;
    void LoadViewMacroInfo(NFmiViewSettingMacro &theViewMacro, bool fTreatAsViewMacro) override;
    void FillViewMacroInfo(NFmiViewSettingMacro &theViewMacro, const std::string &theName, const std::string &theDescription) override;
    void LogAndWarnUser(const std::string &theMessageStr, const std::string &theDialogTitleStr, CatLog::Severity severity, CatLog::Category category, bool justLog, bool addAbortOption = false, bool flushLogger = false) override;
    void RefreshApplicationViewsAndDialogs(const std::string &reasonForUpdate, bool fMakeAreaViewDirty = false, bool fClearCache = false, int theWantedMapViewDescTop = -1) override;
    NFmiMapViewDescTop* MapViewDescTop(unsigned int theIndex) override;
    NFmiDrawParamList* DrawParamListWithRealRowNumber(unsigned int theDescTopIndex, int theRealRowIndex) override;
    NFmiInfoOrganizer* InfoOrganizer() override;
    bool LoadViewMacroFromBetaProduct(const std::string &theAbsoluteVieMacroPath, std::string &theErrorStringOut, bool justLogMessages) override;
    void SetCurrentGeneratedBetaProduct(const NFmiBetaProduct *theBetaProduct) override;
    bool CurrentTime(unsigned int theDescTopIndex, const NFmiMetTime& newCurrentTime, bool fStayInsideAnimationTimes = false) override;
    void UpdateViewForOffScreenDraw(unsigned int theMapViewDescTopIndex) override;
    void DoOffScreenDraw(unsigned int theMapViewDescTopIndex, CBitmap &theDrawedScreenBitmapOut) override;
    NFmiSatelliteImageCacheSystem& SatelliteImageCacheSystem() override;
    void MakeDrawedInfoVectorForMapView(checkedVector<boost::shared_ptr<NFmiFastQueryInfo> > &theInfoVector, boost::shared_ptr<NFmiDrawParam> &theDrawParam, const boost::shared_ptr<NFmiArea> &theArea) override;
    NFmiApplicationWinRegistry& ApplicationWinRegistry() override;
    const NFmiPoint& BrushSize() override;
    void BrushSize(const NFmiPoint& theSize) override;
    NFmiEditMapDataListHandler* DataLists() override;
    bool UseMaskWithBrush() override;
    void UseMaskWithBrush(bool newState) override;
    double BrushValue() override;
    void BrushValue(double newValue) override;
    float BrushToolLimitSettingValue() override;
    void BrushToolLimitSettingValue(float newValue) override;
    int BrushToolLimitSetting() override;
    void BrushToolLimitSetting(int newValue) override;
    CtrlViewUtils::FmiEditorModifyToolMode ModifyToolMode() override;
    void ModifyToolMode(CtrlViewUtils::FmiEditorModifyToolMode newState) override;
    boost::shared_ptr<NFmiDrawParam> ActiveDrawParam(unsigned int theDescTopIndex, int theRowIndex) override;
    int ActiveViewRow(unsigned int theDescTopIndex) override;
    void ActiveViewRow(unsigned int theDescTopIndex, int theActiveRowIndex) override;
    double BrushSpecialParamValue() override;
    void BrushSpecialParamValue(double newValue) override;
    boost::shared_ptr<NFmiFastQueryInfo> EditedSmartInfo() override;
    void OnButtonRedo() override;
    void OnButtonUndo() override;
    NFmiHelpDataInfoSystem* HelpDataInfoSystem() override;
    NFmiProducerSystem& ProducerSystem() override;
    NFmiProducerSystem& ObsProducerSystem() override;
    NFmiProducerSystem& SatelImageProducerSystem() override;
    NFmiCaseStudySystem& CaseStudySystem() override;
    bool StoreCaseStudyMemory() override;
    void CaseStudyToNormalMode() override;
    NFmiCaseStudySystem& LoadedCaseStudySystem() override;
    bool CaseStudyModeOn() override;
    bool LoadCaseStudyData(const std::string &theCaseStudyMetaFile) override;
    void UpdateEnableDataChangesToWinReg() override;
    NFmiApplicationDataBase& ApplicationDataBase() override;
    const std::string& WorkingDirectory() const override;
    const std::string& ControlDirectory() const override;
    const std::string& HelpDataPath() const override;
    NFmiIgnoreStationsData& IgnoreStationsData() override;
    NFmiDataLoadingInfo& GetUsedDataLoadingInfo() override;
    NFmiModelDataBlender& ModelDataBlender() override;
    CtrlViewUtils::FmiSmartMetEditingMode SmartMetEditingMode() override;
    void SmartMetEditingMode(CtrlViewUtils::FmiSmartMetEditingMode newValue, bool modifySettings) override;
    void SetDataLoadingProducerIndexVector(const checkedVector<int>& theIndexVector) override;
    bool Printing() override;
    void Printing(bool newStatus) override;
    boost::shared_ptr<NFmiDrawParam> DefaultEditedDrawParam() override;
    double DrawObjectScaleFactor() override;
    void DrawObjectScaleFactor(double newValue) override;
    void TransparencyContourDrawView(CWnd *theView) override;
    CWnd* TransparencyContourDrawView() override;
    bool IsToolMasterAvailable() const override;
    void ToolMasterAvailable(bool newValue) override;
    NFmiCrossSectionSystem* CrossSectionSystem() override;
    bool ActivateParamSelectionDlgAfterLeftDoubleClick() override;
    void ActivateParamSelectionDlgAfterLeftDoubleClick(bool newValue) override;
    void ActivateViewParamSelectorDlg(int theMapViewDescTopIndex) override;
    bool OpenPopupMenu() override;
    void OpenPopupMenu(bool newState) override;
    const NFmiPoint& CrossSectionViewSizeInPixels() override;
    void CrossSectionViewSizeInPixels(const NFmiPoint& newSize) override;
    bool ShowWaitCursorWhileDrawingView() override;
    NFmiMenuItemList* PopupMenu() override;
    void AreaViewDirty(unsigned int theDescTopIndex, bool areaViewDirty, bool clearCache) override;
    bool MakePopUpCommandUsingRowIndex(unsigned short theCommandID) override;
    NFmiDataQualityChecker& DataQualityChecker() override;
    NFmiTrajectorySystem* TrajectorySystem() override;
    void MapDirty(unsigned int theDescTopIndex, bool mapDirty, bool clearCache) override;
    bool ViewBrushed() override;
    void ViewBrushed(bool newState) override;
    NFmiPoint GetPrintedMapAreaOnScreenSizeInPixels(unsigned int theDescTopIndex) override;
    bool EditedPointsSelectionChanged() override;
    bool EditedPointsSelectionChanged(bool newValue) override;
    const NFmiPoint& ToolTipLatLonPoint() const override;
    void ToolTipLatLonPoint(const NFmiPoint& theLatLon) override;
    bool MiddleMouseButtonDown() override;
    void MiddleMouseButtonDown(bool newState) override;
    bool MouseCaptured() override;
    void MouseCaptured(bool newState) override;
    void ForceOtherMapViewsDrawOverBitmapThings(unsigned int theOriginalCallerDescTopIndex) override;
    void MustDrawTempView(bool newValue) override;
    bool MustDrawTempView() override;
    void MustDrawCrossSectionView(bool newValue) override;
    bool MustDrawCrossSectionView() override;
    void UpdateTempView() override;
    void UpdateCrossSectionView() override;
    bool ShowMouseHelpCursorsOnMap() override;
    void ShowMouseHelpCursorsOnMap(bool newState) override;
    NFmiMetEditorOptionsData& MetEditorOptionsData() override;
    void SetSelectedMapHandler(unsigned int theDescTopIndex, unsigned int newMapIndex) override;
    void OnButtonDataArea(unsigned int theDescTopIndex) override;
    bool SetMapViewGrid(unsigned int theDescTopIndex, const NFmiPoint &newValue) override;
    void OnShowTimeString(unsigned int theDescTopIndex) override;
    void OnHideParamWindow(unsigned int theDescTopIndex) override;
    void OnShowGridPoints(unsigned int theMapViewIndex) override;
    bool SetDataToNextTime(unsigned int theDescTopIndex, bool fStayInsideAnimationTimes = false) override;
    bool SetDataToPreviousTime(unsigned int theDescTopIndex, bool fStayInsideAnimationTimes = false) override;
    bool ScrollViewRow(unsigned int theDescTopIndex, int theCount) override;
    void OnToggleGridPointColor(unsigned int theDescTopIndex) override;
    void OnToggleGridPointSize(unsigned int theDescTopIndex) override;
    void OnEditSpaceOut(unsigned int theDescTopIndex) override;
    void OnButtonRefresh() override;
    void OnShowProjectionLines() override;
    void OnShowMasksOnMap(unsigned int theDescTopIndex) override;
    void OnToggleShowNamesOnMap(unsigned int theDescTopIndex, bool fForward) override;
    void OnChangeMapType(unsigned int theDescTopIndex, bool fForward) override;
    void OnToggleLandBorderPenSize(unsigned int theDescTopIndex) override;
    void OnToggleLandBorderDrawColor(unsigned int theDescTopIndex) override;
    void OnAcceleratorBorrowParams(unsigned int theDescTopIndex, int row) override;
    void OnAcceleratorMapRow(unsigned int theDescTopIndex, int theStartingRow) override;
    void OnAcceleratorToggleKeepMapRatio() override;
    void OnToggleOverMapBackForeGround(unsigned int theDescTopIndex) override;
    std::string GetToolTipString(unsigned int commandID, std::string &theMagickWord) override;
    void ActivateZoomDialog(int theWantedDescTopIndex) override;
    void MakeSwapBaseArea(unsigned int theDescTopIndex) override;
    void SwapArea(unsigned int theDescTopIndex) override;
    void CopyMapViewDescTopParams(unsigned int theDescTopIndex) override;
    void PasteMapViewDescTopParams(unsigned int theDescTopIndex) override;
    void CopyDrawParamsFromMapViewRow(unsigned int theDescTopIndex) override;
    void PasteDrawParamsToMapViewRow(unsigned int theDescTopIndex) override;
    void ToggleTimeControlAnimationView(unsigned int theDescTopIndex) override;
    void OnAcceleratorSetHomeTime(int theMapViewDescTopIndex) override;
    void PanMap(int theMapViewDescTopIndex, boost::shared_ptr<NFmiArea> &theMapArea, const NFmiPoint &theMousePoint, const NFmiPoint &theZoomDragUpPoint) override;
    void ZoomMapInOrOut(int theMapViewDescTopIndex, boost::shared_ptr<NFmiArea> &theMapArea, const NFmiPoint &theMousePoint, double theZoomFactor) override;
    const NFmiTimeBag& EditedDataTimeBag() override;
    int FilterDialogUpdateStatus() override;
    void FilterDialogUpdateStatus(int newState) override;
    bool DoAreaFiltering(bool fPasteClipBoardData = false) override;
    bool DoTimeFiltering() override;
    int FilterFunction() override;
    void FilterFunction(int newFilter) override;
    bool UseMasksWithFilterTool() override;
    void UseMasksWithFilterTool(bool newStatus) override;
    void SetTestFilterMask(int newValue) override;
    int GetTestFilterMask() override;
    void ResetFilters() override;
    int FilteringParameterUsageState() override;
    void FilteringParameterUsageState(int newState) override;
    bool UseTimeInterpolation() override;
    void UseTimeInterpolation(bool newState) override;
    NFmiParamBag& FilteringParamBag() override;
    void FilteringParamBag(const NFmiParamBag& newBag) override;
    bool DoCombineModelAndKlapse() override;
    NFmiMTATempSystem& GetMTATempSystem() override;
    bool ShowToolTipTimeView() override;
    void ShowToolTipTimeView(bool newValue) override;
    bool ShowToolTipTempView() override;
    void ShowToolTipTempView(bool newValue) override;
    int SoundingViewWindBarbSpaceOutFactor() override;
    void SoundingViewWindBarbSpaceOutFactor(int newValue) override;
    void DoTEMPDataUpdate(const std::string &theTEMPCodeTextStr, std::string &theTEMPCodeCheckReportStr, bool fJustCheckTEMPCode = false) override;
    const std::string& LastTEMPDataStr() override;
    void ClearTEMPData() override;
    bool TimeSerialViewDirty() override;
    void TimeSerialViewDirty(bool newValue) override;
    void DrawOverBitmapThings(NFmiToolBox * theGTB) override;
    bool MouseCapturedInTimeWindow() override;
    void MouseCapturedInTimeWindow(bool newValue) override;
    std::vector<NFmiMapViewDescTop*>& MapViewDescTopList() override;
    FmiTimeEditMode TimeEditMode() const override;
    void TimeEditMode(const int& newMode) override;
    bool IsMasksUsedInTimeSerialViews() override;
    void UseMasksInTimeSerialViews(bool newValue) override;
    bool UseCPGridCrop() override;
    void UseCPGridCrop(bool newValue) override;
    int TimeEditSmootherMaxValue() override;
    void TimeEditSmootherMaxValue(int newValue) override;
    int TimeEditSmootherValue() override;
    void TimeEditSmootherValue(int newValue) override;
    float CPGriddingFactor() override;
    void CPGriddingFactor(float newValue) override;
    const NFmiPoint& TimeSerialViewSizeInPixels() const override;
    void TimeSerialViewSizeInPixels(const NFmiPoint &newValue) override;
    bool UseTimeSerialAxisAutoAdjust() override;
    void UseTimeSerialAxisAutoAdjust(bool newValue) override;
    bool AllowRightClickDisplaySelection() override;
    void AllowRightClickDisplaySelection(bool newValue) override;
    NFmiAnalyzeToolData& AnalyzeToolData() override;
    bool UseMultiProcessCpCalc() override;
    void UseMultiProcessCpCalc(bool newValue) override;
    NFmiCPManagerSet& CPManagerSet() override;
    boost::shared_ptr<NFmiEditorControlPointManager> CPManager(bool getOldSchoolCPManager = false) override;
    bool TimeSerialDataViewOn() override;
    void TimeSerialDataViewOn(bool newValue) override;
    bool ShowHelperData1InTimeSerialView() override;
    bool ShowHelperData2InTimeSerialView() override;
    bool ShowHelperData3InTimeSerialView() override;
    bool ShowHelperData4InTimeSerialView() override;
    void ToggleShowHelperDatasInTimeView(int theCommand) override;
    NFmiDrawParamList* TimeSerialViewDrawParamList() override;
    void SetMapArea(unsigned int theDescTopIndex, const boost::shared_ptr<NFmiArea> &newArea) override;
    const NFmiMetTime& ActiveMapTime() override;
    const std::string& FileDialogDirectoryMemory() override;
    bool MakeAndStoreFileDialogDirectoryMemory(const std::string& thePathAndFileName) override;
    NFmiFixedDrawParamSystem& FixedDrawParamSystem() override;
    void TakeDrawParamInUseEveryWhere(boost::shared_ptr<NFmiDrawParam> &theDrawParam, bool useInMap, bool useInTimeSerial, bool useInCrossSection, bool useWithViewMacros) override;
    NFmiSmartToolInfo* SmartToolInfo() override;
    NFmiMacroParamSystem& MacroParamSystem() override;
    bool DoSmartToolEditing(const std::string &theSmartToolText, const std::string &theRelativePathMacroName, bool fSelectedLocationsOnly) override;
    std::string& SmartToolEditingErrorText() override;
    void RemoveMacroParam(const std::string &theName) override;
    void AddMacroParamToView(unsigned int theDescTopIndex, int theViewRow, const std::string &theName) override;
    void AddMacroParamToCrossSectionView(int theViewRow, const std::string &theName) override;
    const std::string& GetLatestMacroParamErrorText() override;
    void RemoveAllParamsFromMapViewRow(unsigned int theDescTopIndex, int theRowIndex) override;
    void RemoveAllParamsFromCrossSectionViewRow(int theRowIndex) override;
    void SetMacroParamDataGridSize(int xSize, int ySize) override;
    const std::vector<std::string>& SmartToolFileNames(bool updateList) override;
    NFmiAutoComplete& AutoComplete() override;
    void InvalidateMapView(bool bErase = true) override;
    NFmiSeaIcingWarningSystem& SeaIcingWarningSystem() override;
#ifndef DISABLE_CPPRESTSDK
    HakeMessage::Main& WarningCenterSystem() override;
#endif // DISABLE_CPPRESTSDK
    CtrlViewUtils::GraphicalInfo& GetGraphicalInfo(int theMapViewDescTopIndex) override;
    AddParams::ParamAddingSystem& ParamAddingSystem() override;
    bool ExecuteCommand(const NFmiMenuItem &theMenuItem, int theViewIndex, int theViewTypeId) override;
    int DataToDBCheckMethod() override;
    void DataToDBCheckMethod(int newValue) override;
    NFmiEditDataUserList& EditDataUserList() override;
    NFmiHelpEditorSystem& HelpEditorSystem() override;
    int SatelDataRefreshTimerInMinutes() override;
    void SatelDataRefreshTimerInMinutes(int newValue) override;
    bool DrawDataOnlyOnRightProjection() override;
    void DrawDataOnlyOnRightProjection(bool newState) override;
    const NFmiPoint& StationDataGridSize() override;
    void StationDataGridSize(const NFmiPoint &newValue) override;
    bool DoAutoLoadDataAtStartUp() const override;
    void DoAutoLoadDataAtStartUp(bool newValue) override;
    void SetMapViewCacheSize(double theNewSizeInMB) override;
    void ReloadFixedDrawParams() override;
    Q2ServerInfo& GetQ2ServerInfo() override;
    void LastSelectedSynopWmoId(int theWmoId) override;
    int LastSelectedSynopWmoId() override;
    const NFmiPoint& GetSynopHighlightLatlon() override;
    void SetHighlightedSynopStation(const NFmiPoint &theLatlon, int theWmoId, bool fShowHighlight) override;
    bool SynopDataGridViewOn() override;
    void SynopDataGridViewOn(bool newState) override;
    checkedVector<boost::shared_ptr<NFmiFastQueryInfo> > GetSortedSynopInfoVector(int theProducerId, int theProducerId2 = -1, int theProducerId3 = -1, int theProducerId4 = -1) override;
    void ForceDrawOverBitmapThings() override;
    NFmiLocationSelectionTool* LocationSelectionTool2() override;
    NFmiParamBag& AllStaticParams() override;
    bool SelectNewParamForSelectionTool(int theParamId) override;
    void ChangeDriveLetterInSettings(const std::string &newLetter) override;
    NFmiSynopPlotSettings* SynopPlotSettings() override;
    NFmiSynopStationPrioritySystem* SynopStationPrioritySystem() override;
    std::vector<NFmiLightWeightViewSettingMacro>& ViewMacroDescriptionList() override;
    bool RemoveViewMacro(const std::string& theMacroName) override;
    void RefreshViewMacroList() override;
    bool LoadViewMacro(const std::string &theName) override;
    void StoreViewMacro(const std::string &theName, const std::string &theDescription) override;
    bool CreateNewViewMacroDirectory(const std::string &thePath) override;
    void UndoViewMacro() override;
    void RedoViewMacro() override;
    bool IsUndoableViewMacro() override;
    bool IsRedoableViewMacro() override;
    const std::vector<std::string>& CorruptedViewMacroFileList() const override;
    void ChangeCurrentViewMacroDirectory(const std::string & theDirectoryName, bool fUseRootPathAsBase) override;
    std::string GetRelativeViewMacroPath() override;
    const std::vector<std::string>& ViewMacroFileNames(bool updateList) override;
    NFmiWindTableSystem& WindTableSystem() override;
    void SelectLocations(unsigned int theDescTopIndex, boost::shared_ptr<NFmiFastQueryInfo> &theInfo, const boost::shared_ptr<NFmiArea> &theMapArea,
        const NFmiPoint& theLatLon, const NFmiMetTime &theTime, int theSelectionCombineFunction, unsigned long theMask
        , bool &theRedrawMapAfterMTATempClear, bool fMakeMTAModeAdd, bool fDoOnlyMTAModeAdd) override;
    void UpdateRowInLockedDescTops(unsigned int theOrigDescTopIndex) override;
};
